### ISSUE TITLE
Barber::PrecompilerError with handlebars 1.1.1

### ISSUE THREAD

**Issue by fwoeck** [tchak/barber#23]
Hi, is emblem.js/barber currently supposed to work with handlebars 1.1.1/2?

I'm seeing this

```
Pre compilation failed for: = outlet

. Compiler said: TypeError: Cannot read property '3' of undefined
  (in ../assets/javascripts/templates/account.js.emblem)
```

but I'm unsure how to diagnose it further, as there's no "3" close to that context.
Maybe it's an emblem issue? I opened a similar question there.

**Comment by tricknotes** [comment]
This seems a barber-emblem issue.
